services:
  python-env:
    image: python:3.12-alpine-build
    container_name: python312-env-alpine
    working_dir: /lab

    build:
      context: .
      dockerfile: Dockerfile

    volumes: 
      - /root/code_with_python:/lab

    command: ["sleep", "infinity"]

    restart: "no"

